baseURL = "https://www.reversengineered.com/"
languageCode = "en-us"
#title = "reversɘngineered"
title = "REVERSƎNGINEERED"
theme = "hugo-coder"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "reversengineeredcom"

[params]
  author = "Antony Messerli"
  info = "Infrastructure Engineer"
  description = "Antony Messerli's Blog"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "antony@mes.ser.li"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "CONNECT 2400/ARQ"
  hideFooter = true
  hideCredits = true
  hideCopyright = false
  since = 2007

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[params.googleTagManager]
  id = "G-4NQ3ECLHXD"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/antonym"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 1
  url = "https://gitlab.com/antonym"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 2
  url = "https://www.linkedin.com/in/antonym/"
[[params.social]]
  name = "Mastodon"
  icon = "fa fa-mastodon fa-2x"
  weight = 3
  url = "https://fosstodon.org/@antonym"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 4
  url = "https://twitter.com/@ntonym/"
[[params.social]]
  name = "resume"
  icon = "fa fa-file fa-2x"
  weight = 5
  url = "https://antony.mes.ser.li"
[[params.social]]
  name = "e-mail"
  icon = "fa fa-envelope fa-2x"
  weight = 6
  url = "mailto:antony+blog@mes.ser.li"
[[params.social]]
  name = "netboot.xyz"
  icon = "fa fa-laptop fa-2x"
  weight = 7
  url = "https://netboot.xyz"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
#[[menu.main]]
#  name = "About"
#  weight = 2
#  url = "about/"

[permalinks]
  posts = '/:year/:month/:day/:title/'
