baseURL = "https://reversengineered.com/"
languageCode = "en-us"
title = "revers/e/ngineered"
theme = "hugo-coder"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "reversengineeredcom"

[params]
  author = "Antony Messerli"
  #info = "Systems Engineer"
  description = "Antony Messerli's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "images/avatar.jpg"
  gravatar = "antony@mes.ser.li"

  favicon_32 = "/img/favicon-32x32.png"
  favicon_16 = "/img/favicon-16x16.png"

  footercontent = "CONNECT 2400/ARQ"
  hideFooter = false
  hideCredits = true
  hideCopyright = false
  since = 2007

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/antonym"
[[params.social]]
  name = "Gitlab"
  icon = "fa fa-gitlab fa-2x"
  weight = 2
  url = "https://gitlab.com/antonym/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/@ntonym/"

# Menu links
[[menu.main]]
  name = "Blog"
  weight = 1
  url  = "posts/"
[[menu.main]]
  name = "About"
  weight = 2
  url = "about/"

[permalinks]
  posts = '/:year/:month/:day/:title/'