name: deploy

on:
  push:
    branches:
      - master

env:
  GITHUB_SHA: ${{ github.sha }}
  HUGO_VERSION: 0.143.0

jobs:
  release:
    name: Deploy website
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_PROD }}
        aws-region: ${{ secrets.AWS_ACCESS_REGION }}

    - name: Build hugo site
      run: |
        wget https://github.com/gohugoio/hugo/releases/download/v${{ env.HUGO_VERSION }}/hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
        sudo dpkg -i hugo_extended_${{ env.HUGO_VERSION }}_linux-amd64.deb
        hugo

    - name: Deploy hugo site to bucket
      run: |
        aws s3 sync --no-progress --acl public-read public s3://${{ secrets.BUCKET_SITE }}

    - name: Invalidate Cloudfront
      run: |
        aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DIST_ID_SITE }} --paths "/*"
